#!/bin/sh

for i in `seq 1 3`; do

ssh -F ssh-config core-0${i} docker pull gcr.io/google_containers/hyperkube:v1.0.6
ssh -F ssh-config core-0${i} docker pull gcr.io/google_containers/podmaster:1.1
ssh -F ssh-config core-0${i} docker pull gcr.io/google_containers/pause:0.8.0

done
